// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyduplrhmycjmqqhctyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZHVwbHJobXljam1xcWhjdHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTAwOTksImV4cCI6MjA2OTI4NjA5OX0.G4B2BqU35PChotGLhT55eI5pmkIUQWXcXSbSdzyuiQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});